project_id = "hhmrwfiomshrkptssays"

[functions.list-tables]
verify_jwt = false

[functions.get-table-data]
verify_jwt = false

[functions.external-db-query]
verify_jwt = false

[functions.insert-data]
verify_jwt = false

[functions.meetings-by-closer]
verify_jwt = false

[functions.delete-meeting]
verify_jwt = false

[functions.clint-analytics]
verify_jwt = false

[functions.fup-forecast-funil]
verify_jwt = false

[functions.fup-forecast-sdr-produtividade]
verify_jwt = false

[functions.fup-forecast-conversao]
verify_jwt = false

[functions.fup-forecast-vendas-produto]
verify_jwt = false
